columnSuffix: null
handle: isStickyMedia
instructions: null
name: 'Media sticks to top?'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
