columnSuffix: null
handle: richText
instructions: null
name: 'Rich text'
searchable: false
settings:
  advancedLinkFields: null
  availableTransforms: ''
  availableVolumes: ''
  characterLimit: null
  css: ".ck.ck-content {\r\n    font-size: 16px;\r\n    line-height: 1.5;\r\n}\r\n\r\n.ck.ck-content p.size-s {\r\n    font-size: .875em;\r\n}\r\n\r\n.ck.ck-content p.size-l {\r\n    font-size: 1.125em;\r\n}\r\n\r\n.ck.ck-content p.size-xl {\r\n    font-size: 1.25em;\r\n}\r\n\r\n.ck.ck-content p.size-xxl {\r\n    font-size: 1.5em;\r\n}"
  cssFile: null
  defaultTransform: null
  defaultUploadLocationSubpath: null
  defaultUploadLocationVolume: null
  fullGraphqlData: true
  headingLevels:
    - '2'
    - '3'
  imageEntryTypeUid: null
  imageFieldUid: null
  imageMode: img
  js: "return {\r\n  heading: {\r\n    options: [\r\n      {\r\n        class: 'ck-heading_paragraph',\r\n        model: 'paragraph',\r\n        title: 'Paragraph',\r\n      },\r\n      {\r\n        class: 'ck-heading_paragraph',\r\n        converterPriority: 'high',\r\n        model: 'paragraphS',\r\n        title: 'Paragraph (Small)',\r\n        view: {\r\n          classes: [\r\n            'size-s',\r\n          ],\r\n          name: 'p',\r\n        },\r\n      },\r\n      {\r\n        class: 'ck-heading_paragraph',\r\n        converterPriority: 'high',\r\n        model: 'paragraphL',\r\n        title: 'Paragraph (Large)',\r\n        view: {\r\n          classes: [\r\n            'size-l',\r\n          ],\r\n          name: 'p',\r\n        },\r\n      },\r\n      {\r\n        class: 'ck-heading_paragraph',\r\n        converterPriority: 'high',\r\n        model: 'paragraphXL',\r\n        title: 'Paragraph (XL)',\r\n        view: {\r\n          classes: [\r\n            'size-xl',\r\n          ],\r\n          name: 'p',\r\n        },\r\n      },\r\n      {\r\n        class: 'ck-heading_paragraph',\r\n        converterPriority: 'high',\r\n        model: 'paragraphXXL',\r\n        title: 'Paragraph (XXL)',\r\n        view: {\r\n          classes: [\r\n            'size-xxl',\r\n          ],\r\n          name: 'p',\r\n        },\r\n      },\r\n    ],\r\n  },\r\n}"
  jsFile: null
  options: null
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  toolbar:
    - heading
    - '|'
    - bold
    - italic
    - link
    - bulletedList
    - numberedList
    - '|'
    - sourceEditing
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
