defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 0d6772dd-d5bb-41e6-a5fa-3ed12a345861 # Blog
handle: blogs
maxAuthors: 1
minAuthors: 1
name: Blogs
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  67aabd95-1a33-42f9-8870-0d419b6007ab: # Renee Boelaars
    enabledByDefault: true
    hasUrls: true
    template: blog/_entry.twig
    uriFormat: 'blog/{slug}'
type: channel
